startupurl: https://www.facebook.com/manototv/app_128953167177144
chainedservers:
  nl:
    addr: 128.199.38.233:443
    pipelined: true
    cert: "-----BEGIN CERTIFICATE-----\nMIICXTCCAgKgAwIBAgIEVRLX0TAMBggqhkjOPQQDAgUAMIGaMQswCQYDVQQGEwJVUzETMBEGA1UE\nCBMKV2FzaGluZ3RvbjEiMCAGA1UEBxMZU2VtaXdlZWtseSBTZW5zYXRpb25hbGlzdDEhMB8GA1UE\nChMYUmVzb3VuZGluZ2x5IEJhbGxvb25pc3RzMRIwEAYDVQQLEwlKb2N1bGFybHkxGzAZBgNVBAMT\nElVuc3ltcGF0aGV0aWMgQ29vbDAeFw0xNTAyMjIwNDI3MzRaFw0xNjAyMjIwNDI3MzRaMIGaMQsw\nCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEiMCAGA1UEBxMZU2VtaXdlZWtseSBTZW5z\nYXRpb25hbGlzdDEhMB8GA1UEChMYUmVzb3VuZGluZ2x5IEJhbGxvb25pc3RzMRIwEAYDVQQLEwlK\nb2N1bGFybHkxGzAZBgNVBAMTElVuc3ltcGF0aGV0aWMgQ29vbDBZMBMGByqGSM49AgEGCCqGSM49\nAwEHA0IABKY+CRk2tUoBuoVrSFD30ARUI6BXvn3fLNAeFAgy+q5UXmkIi/a/bPKaYSnbnoqkZyyZ\ngczmyfGZhCrIv7VvTcSjMjAwMA8GA1UdEQQIMAaHBIDHJukwHQYDVR0OBBYEFK/+N1Fpnr7qHYOM\npQpUcrePUODpMAwGCCqGSM49BAMCBQADRwAwRAIgAUM61RsYlirZAjbkon8+9VxVAWsVv3sFT10i\nipB63fgCIHbTnAAiEf+4OWBKLQm79duYsYhmkRV9q2zVYxI133dy\n-----END
        CERTIFICATE-----\n"
    authtoken: rrIH863YNE6ZP0k4ybQoZ9hZfMjKR4IZAuEJfPx0ScaZuiyeCxbUatn2NPM9zsDb
    weight: 1000000
    qos: 10
    trusted: true
